# Generated by Django 5.2 on 2026-07-25 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0001_initial"),
        ("product", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="customers_count",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ad",
            name="leads_count",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ad",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ad",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="profit",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
