# Generated by Django 5.2 on 2026-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0002_alter_ad_customers_count_alter_ad_leads_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="profit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
