# Generated by Django 5.2 on 2026-07-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_cost_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
