# Generated by Django 5.2 on 2026-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
