# Generated by Django 5.2 on 2026-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_alter_contract_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="cost",
            field=models.IntegerField(default=0),
        ),
    ]
