# Generated by Django 5.2 on 2026-07-25 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0003_alter_contract_cost"),
        ("product", "0003_alter_product_cost_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contracts",
                to="product.product",
            ),
        ),
    ]
