# Generated by Django 5.2 on 2026-07-23 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lead",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
