# Generated by Django 5.2 on 2026-07-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ad", "0001_initial"),
        ("lead", "0002_lead_created_at_lead_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ab",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leads",
                to="ad.ad",
            ),
            preserve_default=False,
        ),
    ]
