# Generated by Django 5.2 on 2026-07-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0003_lead_ab"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="ab",
            new_name="ad",
        ),
    ]
