# Generated by Django 5.2 on 2026-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0004_rename_ab_lead_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="phone",
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
