# Generated by Django 5.2 on 2026-07-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        ("lead", "0002_lead_created_at_lead_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="lead.lead",
            ),
        ),
    ]
