# Generated by Django 5.2 on 2026-07-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_alter_contract_file"),
        ("customer", "0002_alter_customer_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="contract",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="contract.contract",
            ),
            preserve_default=False,
        ),
    ]
