# Generated by Django 5.2 on 2026-07-25 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_contract"),
        ("lead", "0005_alter_lead_email_alter_lead_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="lead.lead",
            ),
        ),
    ]
