name: Code Formatting Check

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install python dependencies
        run: | 
          pip install -r ./requirements.txt
          pip install pylint

      - name: Code Formatting Check
        run: pylint --rcfile .pylintrc ./crm_system/*

